# Generated by Django 4.1.6 on 2023-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('select', models.CharField(max_length=10000000)),
                ('firstname', models.CharField(max_length=10000000)),
                ('lastname', models.CharField(max_length=10000000)),
                ('email', models.CharField(max_length=100000)),
            ],
        ),
    ]
