# Generated by Django 4.1.6 on 2023-06-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_firstname_student_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='select',
            new_name='gender',
        ),
    ]
