# Generated by Django 4.1.6 on 2023-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='salutation',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
