# Generated by Django 4.1.6 on 2023-06-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentprofile_marital_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
