# Generated by Django 4.2.1 on 2023-06-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_studentprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='salutation',
        ),
    ]
