# Generated by Django 4.2.1 on 2023-06-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_studentprofile_marital_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
