# Generated by Django 4.2.1 on 2023-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_delete_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
