# Generated by Django 4.2.1 on 2023-06-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
