# Generated by Django 4.2.1 on 2023-06-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='username',
        ),
    ]
