# Generated by Django 4.2.1 on 2023-06-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_studentprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(max_length=1000000),
        ),
    ]
