# Generated by Django 4.2.1 on 2023-06-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_studentprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='id_student',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student',
            new_name='user',
        ),
    ]
