# Generated by Django 4.2.1 on 2023-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_studentprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='salutation',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
