# Generated by Django 4.2.1 on 2023-06-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_studentprofile_nationality_studentprofile_salutation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='salutation',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(max_length=1000000),
        ),
    ]
