# Generated by Django 4.2.1 on 2023-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_studentprofile_course_alter_studentprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000000)),
                ('course', models.CharField(max_length=100000)),
                ('class_size', models.IntegerField()),
                ('lecturer', models.CharField(max_length=10000000)),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=1000000)),
                ('room', models.CharField(max_length=1000000)),
                ('registered_count', models.IntegerField(default=0)),
            ],
        ),
    ]
