# Generated by Django 4.2.1 on 2023-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_courseregistration_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
