# Generated by Django 4.2.1 on 2023-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_course_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.BooleanField(blank=True),
        ),
    ]
