# Generated by Django 4.2.1 on 2023-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_course_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='registered',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registered',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
