# Generated by Django 4.2.1 on 2023-06-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_courseregistration_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('grade', models.CharField(default='F', max_length=100000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
                ('the_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
    ]
