# Generated by Django 4.2.1 on 2023-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_score',
            field=models.FloatField(),
        ),
    ]
