# Generated by Django 4.2.1 on 2023-06-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_alter_grade_exam_score_alter_grade_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='the_course',
        ),
        migrations.AddField(
            model_name='grade',
            name='the_registered_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.courseregistration'),
            preserve_default=False,
        ),
    ]
