# Generated by Django 4.2.1 on 2023-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_remove_grade_the_course_grade_the_registered_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='the_registered_course',
        ),
        migrations.AddField(
            model_name='grade',
            name='the_registered_course',
            field=models.ManyToManyField(to='students.courseregistration'),
        ),
    ]
