# Generated by Django 4.2.1 on 2023-06-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_remove_grade_the_registered_course_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='the_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=100000),
        ),
    ]
